{% set name = "mailchecker" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mailchecker-{{ version }}.tar.gz
  sha256: 77c446fcf4963c7bd0cbba3db4f2cf1ab129d2bfd8dc95b05a84f7712e22477f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - MailChecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FGRibreau/mailchecker
  summary: Cross-language email validation. Backed by a database of thousands throwable email providers.
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
