{% set name = "mailchecker" %}
{% set version = "4.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mailchecker-{{ version }}.tar.gz
  sha256: 2b1ea88b623cfeae06655683a271747d538d170f8be66da60aeb2f6d0f34d923

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - MailChecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FGRibreau/mailchecker
  summary: Cross-language email validation. Backed by a database of thousands throwable email providers.
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
